server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8001
  context-path: /

spring:
  datasource:
    dynamic:
      primary: gen
      datasource:
        gen:
          driver-class-name: com.mysql.jdbc.Driver
          url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hzero_generator?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
          username: ${SPRING_DATASOURCE_USERNAME:root}
          password: ${SPRING_DATASOURCE_PASSWORD:root}
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/view/

mybatis:
  mapperLocations: classpath:mapper/**/*.xml